language: ruby
rvm:  
  - "1.9.3"  
  #- jruby-19mode # JRuby in 1.9 mode
  #- rbx
  
env:
  - DB=sqlite
  - DB=postgresql
  
before_script:  
  - psql -c 'create database ostaz_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
notifications:
  recipients:
    - eng.balkerm@gmail.com
branches:
  only:
   - develop
#before_script:
 # - bundle exec rake db:migrate db:test:prepare
#before_install: gem install cucumber
#script: 
 # - bundle exec cucumber --trace