language: ruby
rvm:  
  - "1.9.3"  
  
env:
  - DB=sqlite
  
before_script:   
  - bundle exec rake --trace db:migrate db:test:prepare
  #- bundle exec rake --trace db:test:clone
#script:
 # - bundle exec rake cucumber --trace  

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
notifications:
  recipients:
    - eng.balkerm@gmail.com
branches:
  only:
   - develop
script: 
  - bundle exec cucumber