language: ruby
rvm:
  #- "1.8.7"
  #- "1.9.2"
  - "1.9.3"
  #- jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
notifications:
  recipients:
    - eng.balkerm@gmail.com
branches:
  only:
    - develop
before_install: gem install cucumber
script: bundle exec rake cucumber